services:

  sso:
    build: .
    image: kelbri/sso:0.0.2
    container_name: sso
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/config
      - ./storage:/storage
    ports:
      - 44044:44044
      - 8084:8084
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge