services:

  sso:
    build:
      context: .
      dockerfile: Dockerfile
    image: kelbri/sso:0.0.3
    container_name: sso
    ports:
      - "44044:44044"
    volumes:
      - ./config:/app/config
    depends_on:
      - db
      - redis
    networks:
      - sso-network

  db:
    image: postgres:15
    container_name: db
    environment:
        POSTGRES_USER: kelbri
        POSTGRES_PASSWORD: password
        POSTGRES_DB: sso
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sso-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - sso-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge

volumes:
  pgdata:
