services:
  sso:
    build:
      context: .
      dockerfile: Dockerfile
    image: kelbri/sso:0.0.3
    ports:
      - "44044:44044"
    volumes:
      - ./config:/app/config
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
        POSTGRES_USER: kelbri
        POSTGRES_PASSWORD: password
        POSTGRES_DB: sso
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: