name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: gabr@84.252.137.116
      IP: 84.252.137.116
      VERSION: 0.0.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sso:${{ env.VERSION }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sso:${{ env.VERSION }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Setup environment variables
        run: |
          echo CONFIG_PATH=./config/prod.yaml >> .env

      - name: Copy docker-compose.yaml and .env to remote server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ env.HOST }}:~/apps/sso/ &&
          scp -o StrictHostKeyChecking=no .env ${{ env.HOST }}:~/apps/sso/

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.HOST }} "cd ~/apps/sso && docker-compose down && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sso:${{ env.VERSION }} && docker-compose up -d"